spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              redirect-uris:
                - "http://frontend:4200/menu/beverages"
              post-logout-redirect-uris:
                - "http://frontend:4200/menu/beverages"
      client:
        registration:
          google:
            redirect-uri: "http://auth:9000/login/oauth2/code/google"
  datasource:
    url: jdbc:postgresql://auth_db:5432/auth_db

urls:
  paths:
    auth_server: auth
    frontend: frontend

server:
  port: 8080
  locale: uk
