server:
  port: 9000
  locale: uk

urls:
  paths:
    auth_server: http://localhost:9000
    frontend: http://localhost:4200
logging:
  level:
    org.springframework.security: trace
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: replace_it
              client-secret: replace_it
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:4200/menu/beverages"
              post-logout-redirect-uris:
                - "http://localhost:4200/menu/beverages"
              scopes: openid,email,profile,offline_access
            require-authorization-consent: true
            require-proof-key: true
            token:
              access-token-time-to-live: 1440m
              refresh-token-time-to-live: 3d
              reuse-refresh-tokens: true
      client:
        registration:
          google:
            client-id: replace_it
            client-secret: replace_it
            scope: openid,email,profile
            redirect-uri: "http://localhost:9000/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            user-name-attribute: sub

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: prokhovich2@gmail.com
    password: replace_it
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6380
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
